# Generated by Django 3.0.14 on 2023-08-06 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriumFeature',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('feature', models.CharField(choices=[('THREE_D', 1), ('TWO_D', 2), ('DOLBY_AUDIO', 3)], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('cast', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieLanguage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(choices=[('ENGLISH', 1), ('HINDI', 2), ('TAMIL', 3)], max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Auditorium')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeatType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('seatTypeName', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('language', models.CharField(choices=[('ENGLISH', 1), ('HINDI', 2), ('TAMIL', 3)], max_length=255)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Auditorium')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Movie')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('timeofBooking', models.DateTimeField()),
                ('ticketStatus', models.CharField(choices=[('BOOKED', 1), ('PROCESSING', 2), ('CANCELLED', 3)], max_length=255)),
                ('bookedby', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.User')),
                ('seats', models.ManyToManyField(to='app.Seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Theatre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.City')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowSeatType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('price', models.FloatField()),
                ('seatType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SeatType')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShowSeat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('FREE', 1), ('OCCUPIED', 2), ('LOCKED', 3)], max_length=255)),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Show')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='seat',
            name='seatType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.SeatType'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('SUCCESSFULL', 1), ('FAILED', 2)], max_length=255)),
                ('type', models.CharField(choices=[('MONEY', 1), ('REFUND', 2), ('DISCOUNT', 3)], max_length=255)),
                ('provider', models.CharField(choices=[('RAZORPAY', 1), ('PAYU', 2)], max_length=255)),
                ('refID', models.CharField(max_length=255)),
                ('time', models.DateTimeField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.Ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='languages',
            field=models.ManyToManyField(to='app.MovieLanguage'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='features',
            field=models.ManyToManyField(to='app.AuditoriumFeature'),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='theatre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Theatre'),
        ),
    ]
